server:
  port: 8080

client:

opentracing:
  jaeger:
    log-spans: true
    enabled: true
    http-sender:
      url: http://jaeger-collector.default.svc.cluster.local:14268/api/traces
    probabilistic-sampler:
      sampling-rate: 0.2

proxy:
  base_path: ${PROXY_PATH:}
  host_path: ${HOST_PATH:}
  http_proxy_host: ${HTTP_PROXY_HOST:}
  http_proxy_port: ${HTTP_PROXY_PORT:8080}

spring:
  application:
    name: api-rag-demo-service
  servlet:
    multipart:
      max-file-size: 2048MB


metrics:
  open: ${METRICS_OPEN:false}
  platform: os
  namespace: api-rag-demo-service
  application: ${METRICS_APPLICATION:azureMonitor}

azure:
  application-insights:
    connection-string: ${AZURE_CONNECTION_STRING:InstrumentationKey=xxxx}

domain: ${DOMAIN:dev}

leaf-server:
  address: ${LEAF_SERVER_ADDRESS:}

management:
  health:
    elasticsearch:
      enabled: false


diversion:
  diagram:
    fallback-ratio: ${DIVERSION_DIAGRAM_FALLBACK_RATIO:0.8}
    other-ratio: ${DIVERSION_DIAGRAM_OTHER_RATIO:{"20":1,"50":0.65,"100":0.55,"150":0.4,"250":0.25,"350":0.18,"500":0.12,"1000":0.06}}
